base_config: oak_base.yaml

EXP_NAME: "oak_clevr4_texture"
TRAINER:
  SOLVER:
    LR: 0.01
  OAK:
    CLIP_TEXT_REG_WEIGHT: 1.0
    TEXT_INV_REG_WEIGHT: 0.01

DATA:
  NAME: clevr4_texture
  RANDOM_SEED: 0