SAVE_DIR: "saved"
EXP_NAME: "oak_base"
MODEL:
  VARIANT: "ViT-B/16"
  PRETRAINED_PATH: ""
  FEAT_DIM: 512
  GRAD_FROM_BLOCK: 11 # for vision transformers
  VPT:
    PROMPT:
      NUM_TOKENS: 50
      INITIATION: "random"
      PROJECT: -1
      DROPOUT: 0.0
DATA:
  NAME: ""
  ROOT: ""
  DESCRIPTION: ""
  BATCH_SIZE: 128
  NUM_WORKERS: 4
  PROP_TRAIN: 16.0
  PROP_TRAIN_CLASS_WISE: True
  RANDOM_SEED: 0
  USE_SSB_SPLITS: False
  TRANSFORMS:
    NORM_TYPE: "imagenet"
    AUG_TYPE: "imagenet"
    IMAGE_SIZE: 224
    INTERPOLATION: 3
    CROP_PCT: 1.0
    RAND_AUG:
      N: -1
      M: -1
    HERBARIUM_DEFAULT:
      RESIZE_LOWER_BOUND: -1
TRAINER:
  SOLVER:
    NAME: "SGD"
    LR: 0.1
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.00005
  SCHEDULER:
    NAME: "CosineAnnealingLR"
    ETA_MIN_MULTIPLIER: 0.001
  EPOCHS: 50
  LOG_EVERY_N: 10
  TEMPERATURE: 1.0
  SUP_CON_WEIGHT: 0.35
  N_VIEWS: 2
  CONTRAST_UNLABEL_ONLY: False
  MLP_PROJ:
    NUM_LAYERS: 3
    OUT_DIM: 65536
  TEXT_REG_WEIGHT: 0.0
  TEXT_INV_VOCAB: 'ChatGPT'
  TEXT_INV_WEIGHT: 0.0
EVALUATOR:
  EVAL_FUNCS: ["v2"]
  CLUSTER_METHODS: ['sskmeans']
  SSKMEANS:
    RANDOM_STATE: 1
    N_INIT: 10
    TOLERANCE: 0.0001
    MAX_ITERATIONS: 200
    INIT: "k-means++"
    PAIRWISE_BATCH_SIZE: 1024
    N_JOBS: null
    MODE: null
